In [2]:
import numpy as np


In [3]:
a = np.array([1,3,5])
print(a)


[1 3 5]


In [5]:
b = np.array([[4,5,6],[1,2,3]])
print(b)

[[4 5 6]
 [1 2 3]]


In [6]:
print(a*b)

[[ 4 15 30]
 [ 1  6 15]]


In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [11]:
a.dtype

dtype('int64')

In [12]:
a.itemsize

8

In [13]:
a.size

3

In [14]:
b.size

6

In [15]:
b.itemsize

8

In [16]:
b.shape

(2, 3)

In [17]:
b.dtype

dtype('int64')

In [18]:
import time

In [19]:
import numpy as np

In [24]:
#creates array for normal array
arr= list(range(1000000))

#Normal python list
start = time.time()
result = [x*2 for x in arr]
end = time.time()
print("Normal python time;",end-start)


Normal python time; 0.14013934135437012


In [23]:
#creates array for numpy array
p_arr = np.array(arr)

#Numpy array
start= time.time()
result= p_arr*2
end= time.time()
print("Numpy Time:",end-start)

Numpy Time: 0.008454322814941406


In [25]:
c = np.array([4,5,6])
print(c)

[4 5 6]


In [26]:
print(a*c)

[ 4 15 30]


In [27]:
c.ndim

1

In [28]:
c.dtype

dtype('int64')

In [29]:
c.itemsize

8