In [2]:
import numpy as np

In [3]:
a = np.array([2,4,6])
print(a)

[2 4 6]


In [4]:
#total size
print(a.size * a.itemsize)

24


In [5]:
a.dtype


dtype('int64')

In [6]:
b= np.array([5,7,8,9])
print(b)

[5 7 8 9]


In [7]:
print(b[1:3:2])

[7]


In [8]:
print(b[0:4:2])

[5 8]


In [9]:
c= np.array([5,7,8,9,2])
print(c[1:4])

[7 8 9]


In [10]:
d= np.array([7,8,9,10])
print(d[ :2])

[7 8]


In [11]:
a = np.array([5,6,7,8,9])
print(a[2:5])

[7 8 9]


In [12]:
b = np.array([3,4,5,2,6])
print(b[1:4])

[4 5 2]


In [13]:
c = np.array([6,7,8])
print(c)

[6 7 8]


In [14]:
f = np.array([[[2,4],[5,6]],[[7,4],[1,2]]])
print(f)

[[[2 4]
  [5 6]]

 [[7 4]
  [1 2]]]


In [15]:
f[0:1]

array([[[2, 4],
        [5, 6]]])

In [16]:
f[:,1,:]

array([[5, 6],
       [1, 2]])

In [17]:
f[0,::]

array([[2, 4],
       [5, 6]])

In [18]:
f[1,::]

array([[7, 4],
       [1, 2]])

In [19]:
f[1,0,1]

np.int64(4)

In [20]:
f[0,0,1]


np.int64(4)

In [21]:
f

array([[[2, 4],
        [5, 6]],

       [[7, 4],
        [1, 2]]])

In [22]:
f[:,1,:]

array([[5, 6],
       [1, 2]])

In [23]:
f[:,1,:]=[[4,4],[5,5]]

In [24]:
f

array([[[2, 4],
        [4, 4]],

       [[7, 4],
        [5, 5]]])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.zeros((2,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [27]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [28]:
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [29]:
np.ones((3,2,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [30]:
np.full((2,2),55)

array([[55, 55],
       [55, 55]])

In [31]:
np.full((3,2),100)

array([[100, 100],
       [100, 100],
       [100, 100]])

In [32]:
#Random Decimal Number
np.random.rand(4,2)


array([[0.27334387, 0.78138717],
       [0.89872277, 0.99469247],
       [0.61446508, 0.93727395],
       [0.82847311, 0.81603195]])

In [33]:
#Random Integer Values
np.random.randint(11)

8

In [34]:
np.random.randint(5,size=(3,3))

array([[2, 2, 4],
       [0, 3, 2],
       [1, 4, 0]], dtype=int32)

In [35]:
np.random.randint(-2,8,size=(3,3))

array([[ 0,  7,  4],
       [ 2, -1,  5],
       [ 5,  5,  2]], dtype=int32)

In [36]:
#Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
#Repeat an arrray
arr= np.array([[1,2,3]])
rep = np.repeat(arr,3,axis=0)
print(rep)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [38]:
arr= np.array([1,2,3])
rep = np.repeat(arr,3,axis=0)
print(rep)

[1 1 1 2 2 2 3 3 3]


In [39]:
output = np.ones(5,5) + np.zeros(3,3)

TypeError: Cannot interpret '5' as a data type

In [ ]:
output = np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
output[1:4 , 1:4]=z
print(z)
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#be careful in copying arrays:-
a = np.array([3,4,5])
b = a
b[0] = 100
print(a)
print(b)

[100   4   5]
[100   4   5]


In [ ]:
c = np.array([3,4,6])
d = c.copy()
d[0] = 100
print(c)
print(d)

[3 4 6]
[100   4   6]


In [ ]:
# Mathematics
a = np.array([2,4,5,7])
print(a)

[2 4 5 7]


In [ ]:
a+2

array([4, 6, 7, 9])

In [ ]:
a

array([2, 4, 5, 7])

In [ ]:
a-2

array([0, 2, 3, 5])

In [ ]:
a*3

array([ 6, 12, 15, 21])

In [ ]:
a**2

array([ 4, 16, 25, 49])

In [ ]:
b=np.array([1,0,1,0])
b


array([1, 0, 1, 0])

In [ ]:
b+a

array([3, 4, 6, 7])

In [ ]:
a*b

array([2, 0, 5, 0])

In [ ]:
# Matrix Multiplication
a = np.ones((2,3))
print(a)
b= np.full((3,2),2)
print(b)
d = np.matmul(a,b)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)


np.float64(1.0)

In [ ]:
np.linalg.det(d)

np.float64(0.0)

In [ ]:
a = np.array([[1,2],[3,2]])
b = np.array([[4,5],[6,7]])
print(a)

print(b)
np.matmul(a,b)


[[1 2]
 [3 2]]
[[4 5]
 [6 7]]


array([[16, 19],
       [24, 29]])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,8]])
print(a)
print(b)
np.matmul(a,b)

[[1 2]
 [3 4]]
[[4 5]
 [6 8]]


array([[16, 21],
       [36, 47]])

In [ ]:
# Statistics
stats = np.array([[2,3,4],[5,6,7]])
stats

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
np.min(stats)

np.int64(2)

In [ ]:
np.max(stats)

np.int64(7)

In [ ]:
np.min((stats),axis=1)

array([2, 5])

In [ ]:
np.max((stats),axis=1)

array([4, 7])

In [ ]:
np.sum((stats),axis=0)

array([ 7,  9, 11])

In [ ]:
np.sum((stats),axis=1)

array([ 9, 18])

In [ ]:
# Reorganizing arrays
before = np.array([[5,6,7,8],[8,7,4,1]])
after = before.reshape(2,2,2)
print(after)

[[[5 6]
  [7 8]]

 [[8 7]
  [4 1]]]


In [ ]:
before = np.array([[5,6,7,8,11,20],[8,7,4,1,12,30]])
after = before.reshape(2,2,3)
print(after)

[[[ 5  6  7]
  [ 8 11 20]]

 [[ 8  7  4]
  [ 1 12 30]]]


In [ ]:
# Vertically stacking vectors
v1 = np.array([2,3])
v2 = np.array([4,6])

np.vstack([v1,v2,v1,v2])


array([[2, 3],
       [4, 6],
       [2, 3],
       [4, 6]])

In [ ]:
# Horizontal stacking
v1= np.ones((2,2))
v2 = np.zeros((3,3))

np.hstack((v1,v2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
# Load Data From File
filedata = np.genfromtxt('Armstrong Number.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

FileNotFoundError: Armstrong Number.txt not found.

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.array([2,3,4])
b

array([2, 3, 4])

In [ ]:
arr = np.array([55,44,33,22,100,11,161,262,1002])
np.where(arr%2==0)

(array([1, 3, 4, 7, 8]),)

In [ ]:
arr = [[1,0],[0,1]]
np.tile(arr,(2,2))

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [ ]:
arr = np.array([0,8,4,84,0,3,0,2,0,0,67])
np.nonzero(arr)

(array([ 1,  2,  3,  5,  7, 10]),)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])