In [1]:
import numpy as np

In [2]:
print("Numpy version:",np.__version__)
print("Configuration:",np.show_config)

Numpy version: 2.3.4
Configuration: <function show_config at 0x000001BD417E7240>


In [3]:
Null_vector = np.zeros([10])
Null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a = np.array([1,3,5])
print(f"Memory size of array: {a.dtype} and {a.size*a.itemsize}-bytes")
print("OR,")
print(f"Total memory: {a.nbytes}")

Memory size of array: int64 and 24-bytes
OR,
Total memory: 24


In [5]:
# To get the documnetation of the numpy add function from the command line
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [6]:
null = np.zeros(10)
null[4] = 1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
matrix = np.arange(0,9)
print(matrix.reshape(3,3))
# print('OR,')
# print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [104]:
b = np.array([1,2,0,0,4,0])
print(b)
print(np.where(b!=0))
# print('OR,')
# print(np.nonzero(b))

[1 2 0 0 4 0]
(array([0, 1, 4]),)


In [11]:
identity = np.identity(3)
print(identity)
# print('OR,')
# print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
random = np.random.randint(9,size=(3,3,3))
print(random)
# print('OR,')
# floaat = np.random.rand(3,3,3)
# #OR, np.random.random((3,3,3))
# print(floaat)

[[[7 7 2]
  [2 7 2]
  [6 5 2]]

 [[7 2 2]
  [7 1 0]
  [3 7 0]]

 [[2 1 6]
  [2 5 1]
  [7 7 0]]]


In [13]:
random = np.random.rand(10,10)
print(random)
print()
print('Max_value:',random.max())
print('Min_value:',random.min())

#np.random.randint(0,10, (10,10))

[[0.83335011 0.09516918 0.47762741 0.53371629 0.37608749 0.37912339
  0.34945639 0.70240766 0.70478905 0.3671084 ]
 [0.00774175 0.57787875 0.73676994 0.30788205 0.97202911 0.57065778
  0.04082675 0.01151541 0.64228916 0.85445766]
 [0.36105196 0.20371859 0.13390238 0.93175112 0.92851093 0.39279777
  0.78448541 0.83327425 0.10450344 0.64647402]
 [0.72859385 0.39420786 0.61778506 0.21550233 0.18340693 0.46740604
  0.3082946  0.51829754 0.12334632 0.29654883]
 [0.09744742 0.58882367 0.20632548 0.64523175 0.01174552 0.28676734
  0.11799416 0.76206589 0.41430775 0.30675594]
 [0.56933139 0.94611077 0.13189007 0.7915052  0.12525131 0.67069631
  0.64452076 0.19373542 0.31463579 0.6133393 ]
 [0.35974238 0.74810433 0.09430048 0.05207121 0.90838231 0.27612442
  0.8485821  0.97500746 0.67590283 0.01180447]
 [0.67826456 0.29534804 0.74000974 0.7934466  0.65670361 0.93783885
  0.43888861 0.22358563 0.13605874 0.83472484]
 [0.37294888 0.19511004 0.59213333 0.68232912 0.68657592 0.10757291
  0.85439533

In [14]:
random_vector = np.random.randint(1,20, (15,15))
print(random_vector.mean())

9.68


In [15]:
one_inside = np.ones([10,10])
zeros = np.zeros([8,8])
one_inside[1:-1,1:-1] = zeros
print(one_inside)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
# zeros = np.zeros([7,7])
# random = np.random.randint(1,10, (5,5))
# zeros[1:-1,1:-1] = random
# print(zeros)

#-------------or---------------

# a = np.array([1,2,3])
# print(a)
# z = np.pad(a,pad_width=1,mode='constant',constant_values = 0)
# print(z)

#-------------or----------------

# Best_way:-
arr = np.array([4,5,9,3])
zeros = np.zeros((3,len(arr)+2))
zeros[1,1:-1] = arr
print(zeros)



[[0. 0. 0. 0. 0. 0.]
 [0. 4. 5. 9. 3. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
# ALL ABOUT NAN VALUES:-

# np.nan in NumPy means “Not a Number”.
# It is used to represent missing, undefined, or invalid numerical data.
# nan is actually a special floating-point value.
# nan is NOT equal to itself 😅 => Because NaN represents an undefined value.
# np.isnan(arr)      # find NaN values
# np.nanmean(arr)    # mean ignoring NaN
# np.nansum(arr)     # sum ignoring NaN

# np.inf in NumPy means infinity (∞).
# It represents a value that is infinitely large.
# To check infinity: np.isinf()

In [18]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf>np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


In [19]:
# a = np.random.randint(1,10, (5,5))
# a[1,0] = 1
# a[2,1] = 2
# a[3,2] = 3
# a[4,3] = 4
# print(a)

# OR,
# a = np.zeros([5,5])
# arr = np.arange(1,5)
# a[arr,arr-1] = arr
# print(a)

# OR,
z = np.diag(1+np.arange(4),k=-1)
print(z)

# np.diag():-
#np.diag() in NumPy is used to work with the diagonal elements of a matrix.
#k decides which diagonal to use:
#k=0 → main diagonal (default)
#k=1 → upper diagonal
#k=-1 → lower diagonal

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [69]:
# Checkerboard
checker = np.zeros([8,8])
checker[::2,::2] = 1
checker[1::2,1::2]=1
print(checker)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [127]:
arr = np.unravel_index(99,(6,7,8))
print(arr)
array = np.zeros([6,7,8])

array[1,5,3] = 100
print(array)

(np.int64(1), np.int64(5), np.int64(3))
[[[  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0. 100.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.   

In [130]:
# checkerboard using tile():
# In NumPy, the tile() function is used to repeat an array multiple times.
# syntax: np.tile(array, repetitions)
checker = np.array([[1,0],[0,1]])
np.tile(checker,(4,4))
# Meaning of (4, 4):
# 4 → repeat rows 4 times
# 4 → repeat columns 4 times

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [7]:
# Normalize a matrix = arr/norm , norm = np.linalg.norm(arr)

# arr = np.random.randint(1,10, (5,5))
# print("Array:\n",arr)
# print()
# normalized = arr/np.linalg.norm(arr)
# print("Normalized matrix:\n",normalized)
#OR,
arr = np.random.random((5,5))

arr = ((arr - np.mean(arr)) / np.std(arr))
print("Normalized:\n",arr)

# This checks:

# how far each value is from the mean

# Values:

# below mean → negative
# above mean → positive
# equal to mean → 0




Normalized:
 [[-0.92888575  1.0381115  -0.90183359  0.67151724 -0.79714496]
 [-1.38515697  1.16053578 -0.47540744  0.3659863  -0.96500388]
 [-1.3133221  -0.68461077 -0.51721575  1.20460042  1.61436192]
 [ 0.68176882 -1.38415953  0.64855203  0.74344053 -0.5329323 ]
 [ 0.83500565 -1.48776561  1.4849172  -0.2098734   1.13451465]]


In [84]:
# custom = np.random.randint(0,255, (1,4))
# custom[0,3] = 1
# print("rgba",*custom)
#OR,
rgba = np.dtype([("r",np.ubyte),
                ("g",np.ubyte),
                ("b",np.ubyte),
                ("a",np.ubyte)])
print(rgba)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [96]:
a1 = np.random.randint(1,15,(5,3))
b1 = np.random.randint(1,15,(3,2))
print("1st matrix:\n",a1)
print()
print("2nd matrix:\n",b1)
print()
# print("Multiplication of these two matrices:\n",np.matmul(a1,b1))
# OR,
z = np.dot(a1,b1)
print("Multiplication of these two matrices:\n",z)

1st matrix:
 [[ 1  5 10]
 [ 5  6  4]
 [14 12  8]
 [12  3  8]
 [ 7  8  6]]

2nd matrix:
 [[ 3 12]
 [ 5  4]
 [ 7  8]]

Multiplication of these two matrices:
 [[ 98 112]
 [ 73 116]
 [158 280]
 [107 220]
 [103 164]]


In [149]:
arr = np.random.randint(1,20,(1,10))
arr[(arr>3) & (arr<8)] *= -1
print(*arr)

[ 9 10 17 -7 -7  2 13 19 19 19]


In [3]:
#print(sum(range(5),-1)) => 10

from numpy import *
print(sum(range(5),-1))


10


In [11]:
z = np.random.randint(0,5)
print(z)
print(z**z)
print(2<<z>>2)
print(z<-z)
print(1j*z)
print(z/1/1)
print(z<z>z)

4
256
8
False
4j
4.0
False


In [5]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\HP\AppData\Local\Temp\ipykernel_10804\525075671.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))
C:\Users\HP\AppData\Local\Temp\ipykernel_10804\525075671.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))
C:\Users\HP\AppData\Local\Temp\ipykernel_10804\525075671.py:5: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [40]:
np.random.seed(42)
mat = np.random.rand(3,3)
print(mat)
print()
print(np.ceil(mat))


[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [47]:
a = np.array([9,3,5,6,2,11])
b = np.array([5,6,7,8,9,10])
np.intersect1d(a,b)


array([5, 6, 9])

In [81]:
# np.info(exceptions)

# Suicide mode on:
defaults = np.seterr(all = 'ignore')

# Back to sanity:
_=np.seterr(all='warn')
z= np.array([1,2,3])
z = z/0
# z = z*inf
print(z)


[inf inf inf]


C:\Users\HP\AppData\Local\Temp\ipykernel_5012\2033609862.py:9: RuntimeWarning: divide by zero encountered in divide
  z = z/0


In [84]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

# np.emath in NumPy means “extended math.”
# It provides mathematical functions that can handle complex numbers more safely than normal NumPy math functions.
print(np.emath.sqrt(-1))
print(np.sqrt(-1))

False
1j
nan


C:\Users\HP\AppData\Local\Temp\ipykernel_5012\197981220.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))
C:\Users\HP\AppData\Local\Temp\ipykernel_5012\197981220.py:6: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


In [6]:
today = np.datetime64('today')
print("Today:",today)
tomorrow = today + np.timedelta64(1,'D')
yesterday = today - np.timedelta64(1,'D')
print(f"Tomorrow: {tomorrow} \n Yesterday: {yesterday}")

Today: 2026-05-14
Tomorrow: 2026-05-15 
 Yesterday: 2026-05-13


In [69]:
print("------------------------------JULY-2016--------------------------------")
print(np.arange( np.datetime64('2016-07-01'),np.datetime64('2016-08-01'),dtype='datetime64[D]'))

------------------------------JULY-2016--------------------------------
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [85]:
np.random.seed(42)
A = np.random.randint(1,20,(3,3))
B = np.random.randint(1,15,(3,3))
print(A)
print(B)
sum = np.add(A,B)
half = np.divide(A,2)
half = np.negative(half)
print(half)
print(sum)
result = np.matmul(sum,half)
print('((A+B)*(-A/2)):-\n ',result)

[[ 7 15 11]
 [ 8  7 19]
 [11 11  4]]
[[ 8  8  3]
 [ 6  5  2]
 [ 8 12 14]]
[[-3.5 -7.5 -5.5]
 [-4.  -3.5 -9.5]
 [-5.5 -5.5 -2. ]]
[[15 23 14]
 [14 12 21]
 [19 23 18]]
((A+B)*(-A/2)):-
  [[-221.5 -270.  -329. ]
 [-212.5 -262.5 -233. ]
 [-257.5 -322.  -359. ]]


In [128]:
np.random.seed(5)
rand_arr = np.random.random(10)*5
print(rand_arr)
print('--------------Methods for extracting integers from array--------------------')
ceil = np.ceil(rand_arr-1)
ceil = np.abs(ceil)
print('1.astype: ',rand_arr.astype(int))
print('2.ceil: ',ceil)
print('3.floor: ',np.floor(rand_arr))
print('4.floor-division: ',rand_arr//1)

print('5.trunc: ',np.trunc(rand_arr))
# np.trunc() means truncate decimal values.
# It removes the decimal part and keeps only the integer part toward zero.

print('6.modulus-help: ',rand_arr - rand_arr%1)


[1.10996586 4.35366153 1.03359578 4.59305454 2.44205594 3.05871931
 3.82953928 2.59208994 1.48400251 0.93860614]
--------------Methods for extracting integers from array--------------------
1.astype:  [1 4 1 4 2 3 3 2 1 0]
2.ceil:  [1. 4. 1. 4. 2. 3. 3. 2. 1. 0.]
3.floor:  [1. 4. 1. 4. 2. 3. 3. 2. 1. 0.]
4.floor-division:  [1. 4. 1. 4. 2. 3. 3. 2. 1. 0.]
5.trunc:  [1. 4. 1. 4. 2. 3. 3. 2. 1. 0.]
6.modulus-help:  [1. 4. 1. 4. 2. 3. 3. 2. 1. 0.]


In [161]:
mat = np.tile(np.arange(5),(5,1))
mat

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [30]:
def gen_function():
    for x in range (0,10):
        yield x
# print() only displays values — it does NOT send values to fromiter()
# yield makes the function an iterator generator
# print() shows values
# yield gives values
        
z = np.fromiter(gen_function(),dtype=int)
print(z)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
# syntax of linspace: np.linspace(start, stop, num, endpoint=True/False)
z = np.linspace(0,1,11,endpoint=False)
z = z[1:]  # to exclude '0'
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [58]:
np.random.seed(42)
z = np.random.random(10)
print('Before sorting:\n',z)
print()
print("After sorting:\n",np.sort(z))


Before sorting:
 [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]

After sorting:
 [0.05808361 0.15599452 0.15601864 0.37454012 0.59865848 0.60111501
 0.70807258 0.73199394 0.86617615 0.95071431]


In [154]:
# how to measure execution time:
import time
arr = np.array([4,5])
start = time.time()
print('np.sum() =>',np.sum(arr))
end = time.time()
s = end-start
print('Execution time:',s)
# np.sum() is adds of all elements of one array


np.sum() => 9
Execution time: 0.0004229545593261719


In [155]:
arr = np.array([4,5])
z = arr.cumsum(axis = 0)
start = time.time()
print(z[1])
end = time.time()
o = end-start
print('Execution time:',o)


9
Execution time: 0.00037026405334472656


In [156]:
arr = np.array([4,5])
z = np.add.reduce(arr,axis=0)
start = time.time()
print(z)
end = time.time()
t = end-start
print('Execution time:',t)

# So we can use:
 # 1. np.cumsum(arr,axis)
 # 2. np.add.reduce(arr,axis)
# Because these are faster than np.sum() to add elements of same array..

9
Execution time: 0.0004687309265136719


In [157]:
if (o>s and o>t):
    print('o lose!')
elif o<s and o<t:
    print('o won!')
elif t>s and t>o:
    print('t won!')
elif t<s and t<o:
    print('t won!')
else:
    print('s won!')

o won!


In [191]:
a = np.array([1,2,4,8])
b = np.array([1,2,4,8])
# np.equal(a,b) : returns boolean with broadcasting 

print(np.all(a==b))
print(np.array_equal(a,b))
print(np.allclose(a,b))


True


In [4]:
# How to convert array into read-only..
arr = np.array([1,2,6,8])
arr.flags.writeable = False
arr[1]  = 11
arr

ValueError: assignment destination is read-only

In [7]:
# In Cartesian coordinates, a point is described using two numbers: (x,y)
# x = horizontal position (left/right)
# y = vertical position (up/down)

# In polar coordinates, a point is described using: (r,θ)
# r = distance from the origin (center)
# θ (theta) = angle from the positive x-axis (usually measured in degrees or radians)

# np.sin()
# np.cos()
# np.tan()
# np.arcsin() → inverse of sin
# np.arccos() → inverse of cos
# np.arctan() → inverse of tan

np.random.seed(42)
arr = np.random.randint(1,10,(10,2))
print('-----------Cartesian Coordinates--------\n',arr)


r = np.sqrt(np.sum(np.power(arr,2),axis=1))
r = np.round(r,2).reshape(10,1)
print('r:\n',r)

# theta = np.arctan(np.divide(arr))
# np.round(theta,2)

theta = np.arctan(np.divide(arr[0:,1],arr[0:,0]))
theta = np.degrees(theta)
theta = np.round(theta,2).reshape(10,1)
print('theta:\n',theta)

# arr[0:,0]
# arr[0:,1]
print('-----------Polar Coordinates--------\n(r,0)=\n',np.concat((r,theta),axis=1))



-----------Cartesian Coordinates--------
 [[7 4]
 [8 5]
 [7 3]
 [7 8]
 [5 4]
 [8 8]
 [3 6]
 [5 2]
 [8 6]
 [2 5]]
r:
 [[ 8.06]
 [ 9.43]
 [ 7.62]
 [10.63]
 [ 6.4 ]
 [11.31]
 [ 6.71]
 [ 5.39]
 [10.  ]
 [ 5.39]]
theta:
 [[29.74]
 [32.01]
 [23.2 ]
 [48.81]
 [38.66]
 [45.  ]
 [63.43]
 [21.8 ]
 [36.87]
 [68.2 ]]
-----------Polar Coordinates--------
(r,0)=
 [[ 8.06 29.74]
 [ 9.43 32.01]
 [ 7.62 23.2 ]
 [10.63 48.81]
 [ 6.4  38.66]
 [11.31 45.  ]
 [ 6.71 63.43]
 [ 5.39 21.8 ]
 [10.   36.87]
 [ 5.39 68.2 ]]


In [35]:
np.random.seed(42)
arr = np.random.randint(1,100,(10,1))
print(arr)
arr[np.argmax(arr)] = 0
arr

# print(np.argmax(arr,axis=0,out = a) )
# arr[0,0] = arr[2,1] = arr[0,2] = 0

# numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)
# Returns the indices of the maximum values along an axis.

[[52]
 [93]
 [15]
 [72]
 [61]
 [21]
 [83]
 [87]
 [75]
 [75]]


array([[52],
       [ 0],
       [15],
       [72],
       [61],
       [21],
       [83],
       [87],
       [75],
       [75]], dtype=int32)

In [7]:
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area 
z = np.ones((5,5),[('x',float),('y',float)])

# final = np.meshgrid(x,y,copy=False)
# Use copy=False only when:
# memory optimization matters
# you understand views/broadcasting well.


# Z = np.zeros((5,5), [('x',float),('y',float)])    Also we write this..

# Ye structured array ka tareqa hai NumPy me 😄
# Isme ek array ke har element ke andar multiple fields/store hote hain — bilkul database table ki row ki tarah.
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)

# numpy.meshgrid(*xi, copy=True, sparse=False, indexing='xy')
# Return a tuple of coordinate matrices from coordinate vectors.

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [14]:
x = np.array([1,2,3])
y = np.array([4,5,6])
C = np.ones((3,3))
for i in range(0,3):
    for j in range(0,3):
           C[i][j] = np.divide(1,(x[i]-y[j])).round(2)       
print('Cauchy Matrix:\n',C)

Cauchy Matrix:
 [[-0.33 -0.25 -0.2 ]
 [-0.5  -0.33 -0.25]
 [-1.   -0.5  -0.33]]
